name: Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
#   push:
#     branches: [ main ]
#     paths-ignore:
#       - 'README.md'
#       - 'CHANGELOG.md'
#       - 'website/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: 'go.mod'
      id: go

    - name: Run linters
      uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
      with:
        version: latest

    - name: Generate
      run: make generate

    - name: Confirm no diff
      run: |
        git diff --compact-summary --exit-code || \
          (echo "*** Unexpected differences after code generation. Run 'make generate' and commit."; exit 1)

    - name: Build
      run: make build

  test:
    name: 'Acc. Tests (OS: ${{ matrix.os }} / TF: ${{ matrix.terraform }})'
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        terraform:
          - 1.0.x
          - 1.1.x
          - 1.2.x
          - 1.3.x
          - 1.4.x
          - 1.5.x
          - 1.6.x
          - 1.7.x
          - 1.8.x
    steps:

    - name: Check out code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: 'go.mod'
        check-latest: true

    - name: Setup Terraform ${{ matrix.terraform }}
      uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false

    - name: Run acceptance test
      run: make testacc
      env:
        DATA_DIR: "../data"